spring:
  jpa:
    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: "create.sql"
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        hbm2ddl:
#          delimiter: ;
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/dscatalog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
